### ISSUE TITLE
Fix "Unexpected identifier" Error in Gruntfile output

### ISSUE THREAD

**Issue by mgoodenough** [kitajchuk/grunt-init-squarespace#3]
`nautilus.options.sassRoot` missing trailing comma - causes error at line 48

**Comment by kitajchuk** [comment]
Good callout. Fixed here: 4794a1dcecf6db177b74dd23427f75988790ed6c, so follow the steps on updating the grunt template and you should be good.

**Comment by mgoodenough** [comment]
Thanks!
